### PR TITLE
Synchronized with Yii 2.0.13 & PHP 7.2

### PR DESCRIPTION
**Pull request by RichWeber**

### CODE REVIEW

**Comment by igogo5yo** [comment]
@RichWeber can you check why the build is failed, please?
Then I will draft new release.

**Comment by RichWeber** [comment]
Hi, @igogo5yo 

There were next errors: `Failed to clone the git@*********.git repository, try running in interactive mode so that you can enter your GitHub credentials`

But I can't restart these tests

**Comment by igogo5yo** [comment]
@RichWeber, thanks for the contribution.
Release v1.4 was published!

**Comment by RichWeber** [comment]
@igogo5yo Your welcome

**Pull request merged**
